"""adiciona probabilidade

Revision ID: 2b1368b5264a
Revises: e57552ee9425
Create Date: 2026-06-29 01:17:43.338396

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b1368b5264a"
down_revision: str | Sequence[str] | None = "e57552ee9425"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ofertas", sa.Column("vagas", sa.Integer(), nullable=True))
    op.add_column(
        "ofertas", sa.Column("nota_corte_historica", sa.Float(), nullable=True)
    )
    op.add_column(
        "ofertas", sa.Column("cand_vaga_historico", sa.Float(), nullable=True)
    )
    op.add_column("ranking", sa.Column("probabilidade", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ranking", "probabilidade")
    op.drop_column("ofertas", "cand_vaga_historico")
    op.drop_column("ofertas", "nota_corte_historica")
    op.drop_column("ofertas", "vagas")
    # ### end Alembic commands ###
