"""nota enem optativa

Revision ID: d5c4a5a0a8dc
Revises: 2b1368b5264a
Create Date: 2026-06-29 01:31:51.515991

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5c4a5a0a8dc"
down_revision: str | Sequence[str] | None = "2b1368b5264a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ranking", schema=None) as batch_op:
        batch_op.alter_column("nota_enem", existing_type=sa.FLOAT(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ranking", schema=None) as batch_op:
        batch_op.alter_column("nota_enem", existing_type=sa.FLOAT(), nullable=False)

    # ### end Alembic commands ###
