"""Criando estrutura inicial do ranking

Revision ID: e57552ee9425
Revises:
Create Date: 2026-06-29 00:07:59.518264

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e57552ee9425"

down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ofertas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campus", sa.String(), nullable=False),
        sa.Column("periodo", sa.String(), nullable=False),
        sa.Column("curso", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "campus", "periodo", "curso", name="uix_campus_periodo_curso"
        ),
    )
    op.create_index(op.f("ix_ofertas_campus"), "ofertas", ["campus"], unique=False)
    op.create_index(op.f("ix_ofertas_curso"), "ofertas", ["curso"], unique=False)
    op.create_index(op.f("ix_ofertas_id"), "ofertas", ["id"], unique=False)
    op.create_index(op.f("ix_ofertas_periodo"), "ofertas", ["periodo"], unique=False)
    op.create_table(
        "ranking",
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("faculdade", sa.String(length=100), nullable=False),
        sa.Column("curso", sa.String(length=100), nullable=False),
        sa.Column("periodo", sa.String(length=20), nullable=False),
        sa.Column("acertos", sa.Integer(), nullable=False),
        sa.Column("redacao", sa.Float(), nullable=False),
        sa.Column("nota_enem", sa.Float(), nullable=False),
        sa.Column("is_afro", sa.Boolean(), nullable=False),
        sa.Column("is_publica", sa.Boolean(), nullable=False),
        sa.Column("nfc", sa.Float(), nullable=False),
        sa.Column("respostas", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("nome"),
    )
    op.create_index(op.f("ix_ranking_nome"), "ranking", ["nome"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ranking_nome"), table_name="ranking")
    op.drop_table("ranking")
    op.drop_index(op.f("ix_ofertas_periodo"), table_name="ofertas")
    op.drop_index(op.f("ix_ofertas_id"), table_name="ofertas")
    op.drop_index(op.f("ix_ofertas_curso"), table_name="ofertas")
    op.drop_index(op.f("ix_ofertas_campus"), table_name="ofertas")
    op.drop_table("ofertas")
    # ### end Alembic commands ###
